services:
  mongodb:
    image: mongo:7
    container_name: zerotrust-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: zerotrusthr
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: zerotrust-backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017
      DB_NAME: zerotrusthr
    depends_on:
      - mongodb

  opa:
    image: openpolicyagent/opa:1.3.0-envoy-5-static
    container_name: zerotrust-opa
    ports:
      - "8181:8181"
      - "9191:9191"
    command:
      - "run"
      - "--server"
      - "--config-file=/app/config/opa_config.yaml"
      - "--watch"
      - "/app/data"
      - "/app/policies"
    volumes:
      - ./opa/config:/app/config:ro
      - ./opa/data:/app/data:ro
      - ./opa/policies:/app/policies:ro
      - ./test-input.json:/app/test-input.json:ro

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: zerotrust-envoy
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - backend
      - opa

volumes:
  mongo_data: