################################################################################
#  zerotrust_app/default/indexes.conf
#
#  Definisce l'indice 'zerotrust' dove confluiscono tutti i log del progetto.
#  - OPA decision logs
#  - Backend audit logs
#  - Envoy access logs
################################################################################

[zerotrust]
homePath   = $SPLUNK_DB/zerotrust/db
coldPath   = $SPLUNK_DB/zerotrust/colddb
thawedPath = $SPLUNK_DB/zerotrust/thaweddb
# Retention: 30 giorni (sufficiente per un progetto universitario)
frozenTimePeriodInSecs = 2592000
# Max dimensione indice: 5 GB
maxTotalDataSizeMB = 5120
# Tsidx retention
enableTsidxReduction = true
