[zerotrust:audit]
KV_MODE          = json
SHOULD_LINEMERGE = false
TIME_FORMAT      = %Y-%m-%dT%H:%M:%S.%3NZ
TIME_PREFIX      = "timestamp"\s*:\s*"
TRUNCATE         = 50000
FIELDALIAS-resource_name = resource_id AS resource_name

[zerotrust:access]
KV_MODE          = json
SHOULD_LINEMERGE = false
TIME_FORMAT      = %Y-%m-%dT%H:%M:%S.%3NZ
TIME_PREFIX      = "timestamp"\s*:\s*"
TRUNCATE         = 50000
FIELDALIAS-resource_name = resource_id AS resource_name

[zerotrust:splunk_internal]
KV_MODE          = json
SHOULD_LINEMERGE = false

[opa_decision]
KV_MODE          = json
SHOULD_LINEMERGE = false
TIME_FORMAT      = %Y-%m-%dT%H:%M:%SZ
TIME_PREFIX      = "timestamp"\s*:\s*"
FIELDALIAS-username = input.user AS username
FIELDALIAS-resource = result.resource AS resource_name
FIELDALIAS-action   = input.action AS action