# Non usare flush ruleset in Docker Desktop:
# cancellerebbe anche le regole NAT/DOCKER usate da Docker.
# In una VM/Linux reale si può valutare una policy più restrittiva.
# flush ruleset

table inet filter {
  chain input {
    type filter hook input priority 0;
    # In ambiente Docker Desktop teniamo policy accept
    # per non interferire con le regole interne di Docker.
    # In una VM Linux reale questa policy potrebbe diventare drop.
    policy accept;

    # Traffico già stabilito
    ct state established,related accept

    # Loopback
    iif lo accept

    # SSH - utile solo se eseguito su VM/Linux/Raspberry reale
    tcp dport 22 accept comment "SSH"

    # =================================================================
    # MODIFICA: ENTRYPOINT ZERO TRUST CON LOGGING (NFLOG)
    # =================================================================
    # Prima accettavi solo il pacchetto. Ora lo loggiamo inviandolo 
    # al gruppo 1 di NFLOG prima di accettarlo.
    tcp dport 10000 log prefix "ZTA-ENVOY-ACCESS: " group 1 flags all accept comment "Envoy mTLS entrypoint"

    # DEBUG / OPS - solo sviluppo
    tcp dport 9901 accept comment "Envoy admin dev only"
    tcp dport 8000 accept comment "Splunk UI dev only"
    tcp dport 8088 accept comment "Splunk HEC dev only"
    tcp dport 8089 accept comment "Splunk API dev only"

    # DEV ONLY - da rimuovere nella demo finale se non servono test diretti
    tcp dport 3000 accept comment "Backend direct access dev only"
    tcp dport 27017 accept comment "Mongo direct access dev only"
    tcp dport 8181 accept comment "OPA REST API dev only"
    tcp dport 9191 accept comment "OPA ext_authz gRPC dev only"
  }
}