table inet filter {

  chain input {
    type filter hook input priority 0;
    policy drop;

    # 1. traffico già stabilito
    ct state established,related accept

    # 2. loopback
    iif lo accept

    # 3. ICMP base (ping diagnostica)
    ip protocol icmp accept

    # 4. SSH firewall (debug)
    tcp dport 22 accept

    # 5. Splunk UI
    tcp dport 8000 accept

    # 6. HEC logging (IMPORTANTISSIMO per te)
    tcp dport 8088 log prefix "HEC_ACCESS " accept

    # 7. Envoy entrypoint
    tcp dport 10000 log prefix "ENVOY_ACCESS " accept

    # DROP finale con log
    log prefix "INPUT_DROP " drop
  }


  chain forward {
    type filter hook forward priority 0;
    policy drop;

    ct state established,related accept

    ########################################
    # KALI (WAN_NET) → BACKEND (LAN LOGICA)
    ########################################

    # HTTP attack simulation (backend)
    iifname "br-*" ip daddr 172.20.0.6 tcp dport 3000 accept

    # OPA query
    iifname "br-*" ip daddr 172.20.0.4 tcp dport 8181 accept

    # Splunk access
    iifname "br-*" ip daddr 172.20.0.3 tcp dport 8000 accept

    ########################################
    # BLOCCO ATTACCHI TIPICI
    ########################################

    # SYN scan detection
    tcp flags & (syn|fin|rst|psh|ack|urg) == syn log prefix "SYN_SCAN " drop

    # brute force SSH
    tcp dport 22 limit rate 3/minute accept

    # default drop
    log prefix "FORWARD_DROP " drop
  }
}