plugin="/usr/lib/x86_64-linux-gnu/ulogd/ulogd_inppkt_NFLOG.so"
plugin="/usr/lib/x86_64-linux-gnu/ulogd/ulogd_output_JSON.so"
plugin="/usr/lib/x86_64-linux-gnu/ulogd/ulogd_raw2packet_BASE.so"

# Diciamo a ulogd2 di prendere NFLOG gruppo 1, formattarlo in JSON e stamparlo su file
stack=log1:NFLOG,base1:BASE,json1:JSON

[log1]
group=1

[json1]
sync=1
file="/var/log/ulogd/nftables.json"